In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## Load the excel file

In [17]:
file_path = "dataset/WalmartSales.xlsx"

In [19]:
df = pd.read_excel(file_path)

## Display  the first few rows of the dataset

In [22]:
df.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Date,Time,Payment,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,1/5/2019,13:08:00,Ewallet,9.1
1,226-31-3081,A,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3/8/2019,10:29:00,Cash,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,3/3/2019,13:23:00,Credit card,7.4
3,123-19-1176,B,Yangon,Member,Male,Health and beauty,58.22,8,1/27/2019,20:33:00,Ewallet,8.4
4,373-73-7910,C,Yangon,Normal,Male,Sports and travel,86.31,7,2/8/2019,10:37:00,Ewallet,5.3

## A. Calculate the total sales revenue for each transaction

In [25]:
df['Total Revenue'] = df['Unit price'] * df['Quantity']

## Group by City and Branch to analyze performance

In [28]:
city_branch_performance = df.groupby(['City','Branch']).agg({
    'Total Revenue': ['sum', 'mean', 'count'],
    'Invoice ID': 'nunique'
}).reset_index()

## Rename columns for better readability

In [31]:
city_branch_performance.columns = ['City', 'Branch', 'Total Sales Revenue', 'Average Sales Revenue', 'Total Transactions', 'Unique Invoices']

## Display the city and branch performance

In [34]:
city_branch_performance

,City,Branch,Total Sales Revenue,Average Sales Revenue,Total Transactions,Unique Invoices
0,Mandalay,A,34130.09,286.807479,119,119
1,Mandalay,B,37215.93,315.389237,118,118
2,Mandalay,C,29794.62,313.627579,95,95
3,Naypyitaw,A,35985.64,327.142182,110,110
4,Naypyitaw,B,35157.75,322.548165,109,109
5,Naypyitaw,C,34160.14,313.395780,109,109
6,Yangon,A,33647.27,295.151491,114,114
7,Yangon,B,35193.51,311.446991,113,113
8,Yangon,C,32302.43,285.862212,113,113

## B. Calculate the average price of an item sold aat each branch in each city

In [37]:
avg_price_per_branch = df.groupby(['City','Branch'])['Unit price'].mean().reset_index()

In [39]:
avg_price_per_branch.columns = ['City', 'Branch', 'Average Unit price']

In [41]:
avg_price_per_branch

        City Branch  Average Unit price
0   Mandalay      A           53.353866
1   Mandalay      B           56.133305
2   Mandalay      C           57.958316
3  Naypyitaw      A           54.123182
4  Naypyitaw      B           57.785688
5  Naypyitaw      C           57.941009
6     Yangon      A           55.639298
7     Yangon      B           56.011062
8     Yangon      C           52.684602

## C. Convert Date to datetime format

In [44]:
df['Date'] = pd.to_datetime(df['Date'])

In [46]:
df['Month'] = df['Date'].dt.month

In [48]:
df['Year'] = df['Date'].dt.year

## Calculate the total sales revenue for each transaction

In [51]:
df['Total Revenue'] = df['Unit price'] * df['Quantity']

In [53]:
monthly_performance = df.groupby(['Year', 'Month', 'Product line', 'Gender', 'Payment']).agg({
    'Total Revenue': ['sum', 'mean', 'count']
}).reset_index()

## Rename columns

In [56]:
monthly_performance.columns = ['Year', 'Month', 'Product Line', 'Gender', 'Payment Method', 'Total Sales Revenue', 'Average Sales Reveue', 'Total Transactions']

In [63]:
april_2019_data = monthly_performance[(monthly_performance['Year'] == 2019)]

## Display April 2019 data

In [65]:
april_2019_data

,Year,Month,Product Line,Gender,Payment Method,Total Sales Revenue,Average Sales Reveue,Total Transactions
0,2019,1,Electronic accessories,Female,Cash,2731.86,303.540000,9
1,2019,1,Electronic accessories,Female,Credit card,3045.42,435.060000,7
2,2019,1,Electronic accessories,Female,Ewallet,1576.48,225.211429,7
3,2019,1,Electronic accessories,Male,Cash,3380.29,338.029000,10
4,2019,1,Electronic accessories,Male,Credit card,2248.65,281.081250,8
...,...,...,...,...,...,...,...,...
103,2019,3,Sports and travel,Female,Credit card,2863.86,318.206667,9
104,2019,3,Sports and travel,Female,Ewallet,3398.57,424.821250,8
105,2019,3,Sports and travel,Male,Cash,2084.19,260.523750,8
106,2019,3,Sports and travel,Male,Credit card,3633.90,454.237500,8
107,2019,3,Sports and travel,Male,Ewallet,4930.61,352.186429,14